version: '3.8'

services:
  redmine-db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: redmine
      MYSQL_USER: redmine
      MYSQL_PASSWORD: redmine
    volumes:
      - redmine-db-data:/var/lib/mysql
    restart: unless-stopped
  
  ozwell-service:
    build: ./ozwell-service
    ports:
      - "5001:5000"
    volumes:
      - ./.env:/app/.env
    restart: unless-stopped
  
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - redmine
      - ozwell-service


  redmine:
    image: redmine:latest
    ports:
      - "3000:3000"
    environment:
      REDMINE_DB_MYSQL: redmine-db
      REDMINE_DB_DATABASE: redmine
      REDMINE_DB_USERNAME: redmine
      REDMINE_DB_PASSWORD: redmine
      OZWELL_API_KEY: ${OZWELL_API_KEY}
      OZWELL_WORKSPACE_ID: ${OZWELL_WORKSPACE_ID}
      OZWELL_USER_ID: ${OZWELL_USER_ID}
    volumes:
      - redmine-files:/usr/src/redmine/files
      - ./redmine-plugins:/usr/src/redmine/plugins 
      - /Users/sindujakuna/mcp-servers/first_mcp_server/first_mcp_server/ozwell-wrapper.html:/usr/src/redmine/public/ozwell-wrapper.html
    depends_on:
      - redmine-db
      - ozwell-service
    restart: unless-stopped
  

  mcp-server:
    image: mcp-server-stdio
    stdin_open: true
    tty: true
    depends_on:
      - redmine
    # Add any environment variables your MCP server needs
    # environment:
    #   REDMINE_URL: http://redmine:3000

volumes:
  redmine-db-data:
  redmine-files: